[book]
authors = ["Jesse"]
language = "en"
multilingual = false
src = "src"
title = "electrical_bool"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js"]
